In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('C:/Users/kruti/Downloads/Social_Network_Ads.csv')

In [4]:
data

       UserID  Gender  Age  EstimatedSalary      Purchased
0    15624510    Male   19            19000  Not Purchased
1    15810944    Male   35            20000  Not Purchased
2    15668575  Female   26            43000  Not Purchased
3    15603246  Female   27            57000  Not Purchased
4    15804002    Male   19            76000  Not Purchased
..        ...     ...  ...              ...            ...
395  15691863  Female   46            41000      Purchased
396  15706071    Male   51            23000      Purchased
397  15654296  Female   50            20000      Purchased
398  15755018    Male   36            33000  Not Purchased
399  15594041  Female   49            36000      Purchased

[400 rows x 5 columns]

In [7]:
x=data.drop(columns='Purchased')

In [8]:
y=data['Purchased']

In [9]:
x

       UserID  Gender  Age  EstimatedSalary
0    15624510    Male   19            19000
1    15810944    Male   35            20000
2    15668575  Female   26            43000
3    15603246  Female   27            57000
4    15804002    Male   19            76000
..        ...     ...  ...              ...
395  15691863  Female   46            41000
396  15706071    Male   51            23000
397  15654296  Female   50            20000
398  15755018    Male   36            33000
399  15594041  Female   49            36000

[400 rows x 4 columns]

In [13]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
x['Gender']= labelencoder_X.fit_transform(x['Gender'])
print(x)

       UserID  Gender  Age  EstimatedSalary
0    15624510       1   19            19000
1    15810944       1   35            20000
2    15668575       0   26            43000
3    15603246       0   27            57000
4    15804002       1   19            76000
..        ...     ...  ...              ...
395  15691863       0   46            41000
396  15706071       1   51            23000
397  15654296       0   50            20000
398  15755018       1   36            33000
399  15594041       0   49            36000

[400 rows x 4 columns]

In [14]:
from sklearn import tree

#or from sklearn.tree import DecisionTreeClassifier

In [15]:
model=tree.DecisionTreeClassifier()

In [16]:
#build a model
model.fit(x,y)

DecisionTreeClassifier()

In [17]:
#check the score
model.score(x,y)

1.0

In [18]:
x

       UserID  Gender  Age  EstimatedSalary
0    15624510       1   19            19000
1    15810944       1   35            20000
2    15668575       0   26            43000
3    15603246       0   27            57000
4    15804002       1   19            76000
..        ...     ...  ...              ...
395  15691863       0   46            41000
396  15706071       1   51            23000
397  15654296       0   50            20000
398  15755018       1   36            33000
399  15594041       0   49            36000

[400 rows x 4 columns]

In [22]:
model.predict([[15691863,1,46,41000]])

C:\Users\kruti\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Purchased'], dtype=object)

In [21]:
model.predict([[15624510,1,19,19000]])

C:\Users\kruti\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Not Purchased'], dtype=object)